import Link from "next/link";
import { notFound } from "next/navigation";
import Badge from "@/components/ui/Badge";
import Card from "@/components/ui/Card";
import StageTimeline from "@/components/candidates/StageTimeline";
import CandidateEvidenceReport from "@/components/candidate-evidence-report";
import { getCandidateStore } from "@/features/candidates/store";

export const dynamic = "force-dynamic";

export default async function CandidateDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const candidate = getCandidateStore().getCandidate(id);
  if (!candidate) notFound();
  const skillCount = candidate.analyses.reduce((sum, analysis) => sum + analysis.result.skills.length, 0);
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-3"><Link href="/candidates" className="text-xs font-semibold text-slate-500 hover:text-brand-700">← Back to candidates</Link><Link href="/compare" className="text-xs font-semibold text-brand-700 hover:text-brand-500">Compare this candidate →</Link></div>
      <section className="hero-grid overflow-hidden rounded-[28px] bg-slate-950 text-white shadow-[0_24px_60px_rgba(15,23,42,.18)]"><div className="grid gap-6 p-6 lg:grid-cols-[1fr_auto] lg:items-end lg:p-8"><div><div className="flex flex-wrap gap-2"><Badge tone="brand">{candidate.role}</Badge>{candidate.isDemo && <Badge tone="warning">Demo data</Badge>}<Badge tone="positive">File-grounded</Badge></div><h1 className="mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-5xl">{candidate.name}</h1><p className="mt-3 text-sm text-slate-400">Candidate evidence dossier · created {new Date(candidate.appliedAt).toLocaleDateString()}</p></div><dl className="grid grid-cols-3 gap-2"><div className="rounded-xl border border-lime-300/20 bg-lime-300/[.06] p-4"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Evidence index</dt><dd className="mt-1 text-3xl font-semibold text-lime-300">{candidate.verifiedSkillScore}</dd></div><div className="rounded-xl border border-white/10 bg-white/[.04] p-4"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Repositories</dt><dd className="mt-1 text-3xl font-semibold">{candidate.repositoryCount ?? 0}</dd></div><div className="rounded-xl border border-white/10 bg-white/[.04] p-4"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Skill signals</dt><dd className="mt-1 text-3xl font-semibold">{skillCount}</dd></div></dl></div><div className="border-t border-white/10 bg-white/[.025] px-6 py-3 text-xs text-slate-500 lg:px-8">Evidence index is derived from categorical implementation depth, not an AI confidence score.</div></section>
      <div className="grid gap-5 lg:grid-cols-[.35fr_.65fr]"><Card title="Pipeline progress" subtitle="Candidate stage history"><StageTimeline events={candidate.stageHistory} /></Card><Card title="Recruiter summary" subtitle="Evidence available for review"><div className="grid gap-4 sm:grid-cols-3"><div><span className="text-xs text-slate-400">CV claims grounded</span><strong className="mt-1 block text-2xl text-slate-900">{candidate.verifiedClaimCount ?? 0}</strong></div><div><span className="text-xs text-slate-400">Repository reports</span><strong className="mt-1 block text-2xl text-slate-900">{candidate.analyses.length}</strong></div><div><span className="text-xs text-slate-400">Current stage</span><strong className="mt-1 block text-lg capitalize text-slate-900">{candidate.furthestStage.replace("_", " ")}</strong></div></div></Card></div>
      <section><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Project portfolio</p><h2 className="mt-2 text-xl font-semibold tracking-[-.025em] text-slate-950">Repository evidence</h2></div><span className="text-xs text-slate-400">Select a project for focused review</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{candidate.analyses.map((analysis) => <Link key={analysis.id} href={`/candidates/${candidate.id}/projects/${analysis.id}`} className="interactive-card group overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-start justify-between gap-4"><span className="rounded-lg bg-brand-50 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-brand-700">{analysis.projectType}</span><strong className="font-mono text-2xl text-slate-900">{analysis.evidenceIndex}</strong></div><h3 className="mt-7 text-base font-semibold text-slate-900 group-hover:text-brand-700">{analysis.repositoryName}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{analysis.summary}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3 text-[10px] text-slate-400"><span>{analysis.result.patterns.length} patterns · {analysis.result.selectedFiles.length} files</span><span className="font-semibold text-brand-700 transition-transform group-hover:translate-x-1">Inspect →</span></div></Link>)}</div></section>
      <div className="space-y-6">{candidate.analyses.map((analysis) => <CandidateEvidenceReport key={analysis.id} analysis={analysis} />)}</div>
    </div>
  );
}
