import Link from "next/link";
import Badge from "@/components/ui/Badge";
import type { CandidateRepositoryAnalysis } from "@/features/candidates/types";
import type { EvidenceLevel, ResumeSupport } from "@/types/analysis";

function evidenceTone(level: EvidenceLevel): "positive" | "brand" | "warning" | "neutral" {
  if (level === "Strong Evidence") return "positive";
  if (level === "Good Evidence" || level === "Partial Evidence") return "brand";
  if (level === "Limited Evidence") return "warning";
  return "neutral";
}

function supportTone(support: ResumeSupport): "positive" | "brand" | "warning" | "neutral" {
  if (support === "Strongly Supported" || support === "Supported") return "positive";
  if (support === "Partially Supported") return "warning";
  return "neutral";
}

function EvidenceRing({ value }: { value: number }) {
  return <div className="relative grid h-24 w-24 place-items-center"><svg className="absolute inset-0 -rotate-90" viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43" fill="none" stroke="rgba(255,255,255,.1)" strokeWidth="7" /><circle className="metric-ring-path" cx="50" cy="50" r="43" pathLength="100" fill="none" stroke="#b9ff6b" strokeWidth="7" strokeLinecap="round" strokeDasharray="100" strokeDashoffset={100 - value} /></svg><span className="font-mono text-2xl font-semibold text-lime-300">{value}</span></div>;
}

export default function CandidateEvidenceReport({ analysis }: { analysis: CandidateRepositoryAnalysis }) {
  const result = analysis.result;
  const languageTotal = Object.values(result.languages).reduce((sum, value) => sum + value, 0);
  return (
    <article className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-card">
      <header className="hero-grid grid gap-6 bg-slate-950 p-6 text-white lg:grid-cols-[1fr_auto] lg:items-end lg:p-8">
        <div><div className="flex flex-wrap items-center gap-2"><Badge tone="positive">Deterministic evidence</Badge><span className="text-xs text-slate-500">Engine {result.metadata.engineVersion}</span></div><h2 className="mt-4 text-2xl font-semibold tracking-[-.035em] sm:text-3xl">{analysis.repositoryName}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{analysis.summary}</p><div className="mt-4 flex flex-wrap gap-4"><a href={analysis.repositoryUrl} target="_blank" rel="noreferrer" className="inline-flex text-xs font-semibold text-lime-300 hover:text-lime-200">Open public repository ↗</a><Link href={`/candidates/${analysis.candidateId}/projects/${analysis.id}`} className="inline-flex text-xs font-semibold text-white hover:text-lime-300">Open project drill-down →</Link></div></div>
        <div className="flex items-center gap-4"><EvidenceRing value={analysis.evidenceIndex} /><dl className="grid grid-cols-2 gap-2"><div className="col-span-2 rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Project</dt><dd className="mt-1 text-xs font-semibold">{result.projectType}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Archive</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.repositoryFiles}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Evidence</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.selectedEvidenceFiles}</dd></div></dl></div>
      </header>

      <nav className="flex gap-1 overflow-x-auto border-b border-slate-100 bg-white px-4 py-2 sm:px-7" aria-label="Repository report sections">{[["surface","Stack"],["architecture","Architecture"],["patterns","Patterns"],["skills","Skills"],["interview","Interview"]].map(([target,label]) => <a key={target} href={`#${analysis.id}-${target}`} className="whitespace-nowrap rounded-lg px-3 py-2 text-[11px] font-semibold text-slate-500 transition hover:bg-brand-50 hover:text-brand-700">{label}</a>)}</nav>

      <div className="space-y-10 p-5 sm:p-7 lg:p-8">
        <section id={`${analysis.id}-surface`} className="scroll-mt-28"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Repository surface</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Languages, frameworks and tools</h3></div><span className="text-xs text-slate-400">{result.technologies.length} detected signals</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="space-y-3">{Object.entries(result.languages).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([language, bytes]) => <div key={language}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium text-slate-700">{language}</span><span className="tnum text-slate-400">{languageTotal ? Math.round(bytes/languageTotal*100) : 0}%</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="chart-bar h-full rounded-full bg-brand-600" style={{ width: `${languageTotal ? Math.max(2, bytes/languageTotal*100) : 0}%` }} /></div></div>)}</div><div className="flex flex-wrap content-start gap-2">{result.technologies.map((technology) => <div key={technology.name} className="interactive-card rounded-xl border border-slate-200 bg-slate-50 px-3 py-2"><span className="block text-[9px] font-semibold uppercase tracking-wider text-slate-400">{technology.category}</span><strong className="mt-1 block text-sm text-slate-800">{technology.name}</strong></div>)}</div></div></section>

        <section id={`${analysis.id}-architecture`} className="scroll-mt-28"><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Architecture reading</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{result.architecture.purpose}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{result.architecture.overview}</p></div><div className="rounded-xl bg-[#eef1eb] p-5"><h4 className="text-sm font-semibold text-slate-900">Complexity indicators</h4><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Top-level areas</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.topLevelAreas}</dd></div><div><dt className="text-slate-400">Languages</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.languages}</dd></div><div><dt className="text-slate-400">Boundaries</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.architecturalBoundaries}</dd></div><div><dt className="text-slate-400">Test files</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.testFiles}</dd></div></dl>{result.complexity.signals.length > 0 && <ul className="mt-4 space-y-2">{result.complexity.signals.map((signal) => <li key={signal} className="flex gap-2 text-xs text-slate-600"><span className="text-brand-700">✓</span>{signal}</li>)}</ul>}</div></div><div className="mt-5 rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><div className="flex items-center justify-between"><h4 className="text-xs font-semibold uppercase tracking-[.14em] text-lime-300">Repository topology</h4><span className="font-mono text-[9px] text-slate-500">Path-derived map</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{result.architecture.majorModules.slice(0,8).map((module, index) => <div key={module} className="relative rounded-xl border border-white/10 bg-white/[.04] p-3 transition hover:-translate-y-0.5 hover:border-lime-300/30"><span className="font-mono text-[9px] text-slate-600">M{String(index + 1).padStart(2,"0")}</span><strong className="mt-4 block break-all text-xs text-slate-200">{module}</strong>{index < Math.min(result.architecture.majorModules.length,8) - 1 && <span className="absolute -right-2 top-1/2 hidden h-px w-2 bg-lime-300/40 lg:block" />}</div>)}</div>{result.architecture.boundaries.length > 0 && <div className="mt-5 border-t border-white/10 pt-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-slate-500">Detected boundaries</span><div className="mt-2 flex flex-wrap gap-2">{result.architecture.boundaries.map((file) => <code key={file} className="rounded-md bg-white/[.06] px-2 py-1 text-[9px] text-lime-300">{file}</code>)}</div></div>}</div></section>

        {result.strengths.length > 0 && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Grounded strengths</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{result.strengths.map((strength) => <article key={strength.title} className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4"><h4 className="text-sm font-semibold text-emerald-950">{strength.title}</h4><p className="mt-2 text-xs leading-5 text-emerald-800">{strength.explanation}</p><code className="mt-3 block break-all text-[10px] text-emerald-700">{strength.files.join(" · ")}</code></article>)}</div></section>}

        <section id={`${analysis.id}-patterns`} className="scroll-mt-28"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Implementation evidence</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Patterns found in real source files</h3></div>{result.patterns.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{result.patterns.map((pattern) => <article key={pattern.name} className="interactive-card rounded-xl border border-slate-200 p-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-brand-700">{pattern.category}</span><h4 className="mt-3 text-sm font-semibold text-slate-900">{pattern.name}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{pattern.summary}</p><code className="mt-3 block break-all text-[10px] text-slate-400">{pattern.files.slice(0,3).join(" · ")}</code></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-500">No supported implementation pattern crossed the deterministic evidence threshold in the selected files.</div>}</section>

        <section id={`${analysis.id}-skills`} className="scroll-mt-28"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Skill evidence</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Implementation depth by skill</h3><p className="mt-2 text-xs text-slate-400">Strong=4, Good=3, Partial=2, Limited=1. Dependency-only signals cannot exceed Limited.</p></div><div className="mt-5 space-y-3">{result.skills.map((skill) => <details key={skill.skill} className="group rounded-xl border border-slate-200 bg-white transition open:border-brand-200 open:shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><strong className="text-sm text-slate-900">{skill.skill}</strong><p className="mt-1 text-xs text-slate-500">{skill.explanation}</p></div><div className="flex items-center gap-2"><Badge tone={evidenceTone(skill.level)}>{skill.level}</Badge><span className="text-slate-400 transition group-open:rotate-45">+</span></div></summary><div className="grid gap-px border-t border-slate-100 bg-slate-100 md:grid-cols-2">{skill.evidence.map((evidence, index) => <div key={`${evidence.file}-${index}`} className="bg-white p-4"><code className="break-all text-[10px] font-semibold text-brand-700">{evidence.file}</code><strong className="mt-2 block text-xs text-slate-800">{evidence.summary}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{evidence.implementationExample}</p></div>)}</div></details>)}</div></section>

        {result.resumeVerification && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">CV verification</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Claims compared with this repository</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{result.resumeVerification.claims.map((claim) => <article key={`${claim.claim}-${claim.support}`} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><strong className="text-sm text-slate-900">{claim.claim}</strong><Badge tone={supportTone(claim.support)}>{claim.support}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">{claim.explanation}</p>{claim.files.length > 0 && <code className="mt-3 block break-all text-[10px] text-brand-700">{claim.files.join(" · ")}</code>}</article>)}</div></section>}

        <section id={`${analysis.id}-interview`} className="scroll-mt-28 grid gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-amber-700">Evidence gaps</p><div className="mt-4 space-y-2">{result.gaps.map((gap) => <div key={gap.area} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><strong className="text-sm text-amber-950">{gap.area}</strong><p className="mt-1 text-xs leading-5 text-amber-800">{gap.explanation}</p></div>)}</div></div><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Repository-specific interview</p><ol className="mt-4 space-y-2">{result.interviewQuestions.map((question, index) => <li key={`${question.question}-${index}`} className="interactive-card rounded-xl border border-slate-200 p-4"><div className="flex gap-2 text-[9px] font-semibold uppercase tracking-wider text-slate-400"><span>{String(index + 1).padStart(2,"0")}</span><span>·</span><span>{question.difficulty}</span><span>·</span><span>{question.relatedSkill}</span></div><strong className="mt-2 block text-sm leading-6 text-slate-900">{question.question}</strong><p className="mt-2 text-[11px] leading-5 text-slate-500">{question.relevance}</p><code className="mt-2 block break-all text-[10px] text-brand-700">{question.files.join(" · ")}</code></li>)}</ol></div></section>

        <details className="rounded-xl border border-slate-200 bg-slate-50"><summary className="flex cursor-pointer list-none items-center justify-between p-4 text-sm font-semibold text-slate-800">Source inspection manifest <span className="font-mono text-[10px] font-normal text-slate-400">{result.selectedFiles.length} selected files +</span></summary><div className="grid gap-px border-t border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{result.selectedFiles.map((file) => <div key={file.path} className="bg-white p-3"><code className="block break-all text-[10px] font-semibold text-brand-700">{file.path}</code><span className="mt-1 block text-[10px] text-slate-400">{file.selectionReason} · {file.size.toLocaleString()} bytes{file.truncated ? " · truncated" : ""}</span></div>)}</div></details>
      </div>
    </article>
  );
}
