import RequirementBriefing from "@/components/analysis/RequirementBriefing";
import InterviewQuestionCard from "@/components/analysis/InterviewQuestionCard";
import Link from "next/link";
import Badge from "@/components/ui/Badge";
import type { CandidateRepositoryAnalysis } from "@/features/candidates/types";
import { localizeAnalysisText, translate, type Locale } from "@/i18n/translations";
import type { EvidenceLevel, ResumeSupport } from "@/types/analysis";

function evidenceTone(level: EvidenceLevel): "positive" | "brand" | "warning" | "neutral" {
  if (level === "Strong Evidence") return "positive";
  if (level === "Good Evidence" || level === "Partial Evidence") return "brand";
  if (level === "Limited Evidence") return "warning";
  return "neutral";
}

function supportTone(support: ResumeSupport): "positive" | "brand" | "warning" | "neutral" {
  if (support === "Strongly Supported" || support === "Supported") return "positive";
  if (support === "Partially Supported") return "warning";
  return "neutral";
}

function EvidenceRing({ value }: { value: number }) {
  return <div className="relative grid h-24 w-24 shrink-0 place-items-center" aria-label={`${value} / 100`}><svg className="absolute inset-0 -rotate-90" viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43" fill="none" stroke="rgba(255,255,255,.1)" strokeWidth="7" /><circle className="metric-ring-path" cx="50" cy="50" r="43" pathLength="100" fill="none" stroke="#b9ff6b" strokeWidth="7" strokeLinecap="round" strokeDasharray="100" strokeDashoffset={100 - value} /></svg><span className="font-mono text-2xl font-semibold text-lime-300">{value}</span></div>;
}

export default function CandidateEvidenceReport({ analysis, locale }: { analysis: CandidateRepositoryAnalysis; locale: Locale }) {
  const result = analysis.result;
  const languageTotal = Object.values(result.languages).reduce((sum, value) => sum + value, 0);
  const t = (key: string, values: Record<string, string | number> = {}) => translate(locale, key, values);
  const l = (text: string) => localizeAnalysisText(locale, text);

  return (
    <article className="report-surface overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-card">
      <header className="hero-grid grid gap-6 bg-slate-950 p-5 text-white sm:p-6 lg:grid-cols-[1fr_auto] lg:items-end lg:p-8">
        <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge tone="positive">{t("Deterministic evidence")}</Badge><span className="text-xs text-slate-500">{t("Engine {version}", { version: result.metadata.engineVersion })}</span></div><h2 className="tech-ltr mt-4 break-all text-start text-2xl font-semibold tracking-[-.035em] sm:text-3xl">{analysis.repositoryName}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{l(analysis.summary)}</p><div className="mt-4 flex flex-wrap gap-4"><a href={analysis.repositoryUrl} target="_blank" rel="noreferrer" dir="ltr" className="inline-flex min-h-11 items-center text-xs font-semibold text-lime-300 hover:text-lime-200">{t("Open public repository")} ↗</a><Link href={`/candidates/${analysis.candidateId}/projects/${analysis.id}`} className="inline-flex min-h-11 items-center text-xs font-semibold text-white hover:text-lime-300">{t("Open project drill-down")} <span className="directional-icon ms-1">→</span></Link></div></div>
        <div className="flex flex-wrap items-center gap-4 sm:flex-nowrap"><EvidenceRing value={analysis.evidenceIndex} /><dl className="grid min-w-0 flex-1 grid-cols-2 gap-2"><div className="col-span-2 rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">{t("Project")}</dt><dd className="mt-1 text-xs font-semibold">{l(result.projectType)}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">{t("Archive")}</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.repositoryFiles}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">{t("Evidence")}</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.selectedEvidenceFiles}</dd></div></dl></div>
      </header>

      <nav className="flex gap-1 overflow-x-auto border-b border-slate-100 bg-white px-4 py-2 sm:px-7" aria-label={t("Repository report sections")}>{[["surface", "Stack"], ["architecture", "Architecture"], ["patterns", "Patterns"], ["skills", "Skills"], ["interview", "Interview"]].map(([target, label]) => <a key={target} href={`#${analysis.id}-${target}`} className="min-h-11 whitespace-nowrap rounded-lg px-3 py-2.5 text-[11px] font-semibold text-slate-500 transition hover:bg-brand-50 hover:text-brand-700">{t(label)}</a>)}</nav>

      <div className="space-y-10 p-5 sm:p-7 lg:p-8">
        <section id={`${analysis.id}-surface`} className="scroll-mt-28"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Repository surface")}</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{t("Languages, frameworks and tools")}</h3></div><span className="text-xs text-slate-400">{t("{count} detected signals", { count: result.technologies.length })}</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="space-y-3">{Object.entries(result.languages).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([language, bytes]) => <div key={language}><div className="mb-1.5 flex justify-between text-xs"><span className="tech-ltr font-medium text-slate-700">{language}</span><span className="tnum text-slate-400">{languageTotal ? Math.round(bytes / languageTotal * 100) : 0}%</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="chart-bar h-full rounded-full bg-brand-600" style={{ width: `${languageTotal ? Math.max(2, bytes / languageTotal * 100) : 0}%` }} /></div></div>)}</div><div className="flex flex-wrap content-start gap-2">{result.technologies.map((technology) => <div key={technology.name} className="interactive-card rounded-xl border border-slate-200 bg-slate-50 px-3 py-2"><span className="block text-[9px] font-semibold uppercase tracking-wider text-slate-400">{l(technology.category)}</span><strong dir="ltr" className="mt-1 block text-start text-sm text-slate-800">{technology.name}</strong></div>)}</div></div></section>

        <section id={`${analysis.id}-architecture`} className="scroll-mt-28"><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Architecture reading")}</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{l(result.architecture.purpose)}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{l(result.architecture.overview)}</p></div><div className="rounded-xl bg-[#eef1eb] p-5"><h4 className="text-sm font-semibold text-slate-900">{t("Complexity indicators")}</h4><dl className="mt-4 grid grid-cols-2 gap-3 text-xs">{[["Top-level areas", result.complexity.topLevelAreas], ["Languages", result.complexity.languages], ["Boundaries", result.complexity.architecturalBoundaries], ["Test files", result.complexity.testFiles]].map(([label, value]) => <div key={label}><dt className="text-slate-400">{t(String(label))}</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{value}</dd></div>)}</dl>{result.complexity.signals.length > 0 && <ul className="mt-4 space-y-2">{result.complexity.signals.map((signal) => <li key={signal} className="flex gap-2 text-xs text-slate-600"><span className="text-brand-700">✓</span><span>{l(signal)}</span></li>)}</ul>}</div></div><div className="mt-5 rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-xs font-semibold uppercase tracking-[.14em] text-lime-300">{t("Repository topology")}</h4><span className="font-mono text-[9px] text-slate-500">{t("Path-derived map")}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{result.architecture.majorModules.slice(0, 8).map((module, index) => <div key={module} dir="ltr" className="relative rounded-xl border border-white/10 bg-white/[.04] p-3 text-start transition hover:-translate-y-0.5 hover:border-lime-300/30"><span className="font-mono text-[9px] text-slate-600">M{String(index + 1).padStart(2, "0")}</span><strong className="mt-4 block break-all text-xs text-slate-200">{module}</strong></div>)}</div>{result.architecture.boundaries.length > 0 && <div className="mt-5 border-t border-white/10 pt-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-slate-500">{t("Detected boundaries")}</span><div className="mt-2 flex flex-wrap gap-2" dir="ltr">{result.architecture.boundaries.map((file) => <code key={file} className="rounded-md bg-white/[.06] px-2 py-1 text-[9px] text-lime-300">{file}</code>)}</div></div>}</div></section>

        {result.strengths.length > 0 && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Grounded strengths")}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{result.strengths.map((strength) => <article key={strength.title} className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4"><h4 className="text-sm font-semibold text-emerald-950">{l(strength.title)}</h4><p className="mt-2 text-xs leading-5 text-emerald-800">{l(strength.explanation)}</p><code dir="ltr" className="mt-3 block break-all text-start text-[10px] text-emerald-700">{strength.files.join(" · ")}</code></article>)}</div></section>}

        <section id={`${analysis.id}-patterns`} className="scroll-mt-28"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Implementation evidence")}</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{t("Patterns found in real source files")}</h3>{result.patterns.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{result.patterns.map((pattern) => <article key={pattern.name} className="interactive-card rounded-xl border border-slate-200 p-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-brand-700">{l(pattern.category)}</span><h4 className="mt-3 text-sm font-semibold text-slate-900">{l(pattern.name)}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{l(pattern.summary)}</p><code dir="ltr" className="mt-3 block break-all text-start text-[10px] text-slate-400">{pattern.files.slice(0, 3).join(" · ")}</code></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-500">{t("No supported implementation pattern crossed the deterministic evidence threshold in the selected files.")}</div>}</section>

        <section id={`${analysis.id}-skills`} className="scroll-mt-28"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Skill evidence")}</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{t("Implementation depth by skill")}</h3><p className="mt-2 text-xs text-slate-400">{t("Strong=4, Good=3, Partial=2, Limited=1. Dependency-only signals cannot exceed Limited.")}</p><div className="mt-5 space-y-3">{result.skills.map((skill) => <details key={skill.skill} className="group rounded-xl border border-slate-200 bg-white transition open:border-brand-200 open:shadow-sm"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-3 p-4"><div className="min-w-0"><strong dir="ltr" className="block truncate text-start text-sm text-slate-900">{skill.skill}</strong><p className="mt-1 text-xs text-slate-500">{l(skill.explanation)}</p></div><div className="flex shrink-0 items-center gap-2"><Badge tone={evidenceTone(skill.level)}>{t(skill.level)}</Badge><span className="text-slate-400 transition group-open:rotate-45">+</span></div></summary><div className="grid gap-px border-t border-slate-100 bg-slate-100 md:grid-cols-2">{skill.evidence.map((evidence, index) => <div key={`${evidence.file}-${index}`} className="bg-white p-4"><code dir="ltr" className="block break-all text-start text-[10px] font-semibold text-brand-700">{evidence.file}</code><strong className="mt-2 block text-xs text-slate-800">{l(evidence.summary)}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{l(evidence.implementationExample)}</p></div>)}</div></details>)}</div></section>

        <RequirementBriefing jobMatch={result.jobMatch} locale={locale} />

        {result.resumeVerification && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("CV verification")}</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{t("Claims compared with this repository")}</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{result.resumeVerification.claims.map((claim) => <article key={`${claim.claim}-${claim.support}`} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><strong className="text-sm text-slate-900">{claim.claim}</strong><Badge tone={supportTone(claim.support)}>{t(claim.support)}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">{l(claim.explanation)}</p>{claim.files.length > 0 && <code dir="ltr" className="mt-3 block break-all text-start text-[10px] text-brand-700">{claim.files.join(" · ")}</code>}</article>)}</div></section>}

        <section id={`${analysis.id}-interview`} className="report-section scroll-mt-28 grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
          <div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-amber-700">{t("Evidence gaps")}</p><p className="mt-2 text-xs leading-5 text-slate-500">{t("Use gaps as interview probes, not conclusions about candidate ability.")}</p><div className="mt-4 space-y-2">{result.gaps.map((gap) => <div key={gap.area} className="rounded-xl border border-amber-200 bg-amber-50/75 p-4"><strong className="text-sm text-amber-950">{l(gap.area)}</strong><p className="mt-1 text-xs leading-5 text-amber-800">{l(gap.explanation)}</p></div>)}</div></div>
          <div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">{t("Repository-specific interview")}</p><p className="mt-2 text-xs leading-5 text-slate-500">{t("Each prompt is tied to implementation evidence and includes a recruiter-friendly reason to ask.")}</p><ol className="mt-4 space-y-3">{result.interviewQuestions.map((question, index) => <InterviewQuestionCard key={`${question.question}-${index}`} question={question} index={index} locale={locale} />)}</ol></div>
        </section>

        <details className="rounded-xl border border-slate-200 bg-slate-50"><summary className="flex min-h-12 cursor-pointer list-none flex-wrap items-center justify-between gap-2 p-4 text-sm font-semibold text-slate-800">{t("Source inspection manifest")} <span className="font-mono text-[10px] font-normal text-slate-400">{t("{count} selected files", { count: result.selectedFiles.length })} +</span></summary><div className="grid gap-px border-t border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{result.selectedFiles.map((file) => <div key={file.path} className="min-w-0 bg-white p-3"><code dir="ltr" className="block break-all text-start text-[10px] font-semibold text-brand-700">{file.path}</code><span className="mt-1 block text-[10px] text-slate-400">{l(file.selectionReason)} · {file.size.toLocaleString(locale === "ar" ? "ar-SA" : "en-US")} {t("bytes")}{file.truncated ? ` · ${t("truncated")}` : ""}</span></div>)}</div></details>
      </div>
    </article>
  );
}
