import Badge from "@/components/ui/Badge";
import type { CandidateRepositoryAnalysis } from "@/features/candidates/types";
import type { EvidenceLevel, ResumeSupport } from "@/types/analysis";

function evidenceTone(level: EvidenceLevel): "positive" | "brand" | "warning" | "neutral" {
  if (level === "Strong Evidence") return "positive";
  if (level === "Good Evidence" || level === "Partial Evidence") return "brand";
  if (level === "Limited Evidence") return "warning";
  return "neutral";
}

function supportTone(support: ResumeSupport): "positive" | "brand" | "warning" | "neutral" {
  if (support === "Strongly Supported" || support === "Supported") return "positive";
  if (support === "Partially Supported") return "warning";
  return "neutral";
}

export default function CandidateEvidenceReport({ analysis }: { analysis: CandidateRepositoryAnalysis }) {
  const result = analysis.result;
  const languageTotal = Object.values(result.languages).reduce((sum, value) => sum + value, 0);
  return (
    <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card">
      <header className="grid gap-6 bg-slate-950 p-6 text-white lg:grid-cols-[1fr_auto] lg:items-end lg:p-8">
        <div><div className="flex flex-wrap items-center gap-2"><Badge tone="positive">Deterministic evidence</Badge><span className="text-xs text-slate-500">Engine {result.metadata.engineVersion}</span></div><h2 className="mt-4 text-2xl font-semibold tracking-[-.03em] sm:text-3xl">{analysis.repositoryName}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{analysis.summary}</p><a href={analysis.repositoryUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-semibold text-lime-300">Open public repository ↗</a></div>
        <dl className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2"><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Project</dt><dd className="mt-1 text-xs font-semibold">{result.projectType}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Evidence index</dt><dd className="mt-1 text-lg font-semibold text-lime-300">{analysis.evidenceIndex}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Archive files</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.repositoryFiles}</dd></div><div className="rounded-lg border border-white/10 p-3"><dt className="text-[9px] uppercase tracking-wider text-slate-500">Evidence files</dt><dd className="mt-1 text-lg font-semibold">{result.complexity.selectedEvidenceFiles}</dd></div></dl>
      </header>

      <div className="space-y-10 p-5 sm:p-7 lg:p-8">
        <section><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Repository surface</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Languages, frameworks and tools</h3></div><span className="text-xs text-slate-400">{result.technologies.length} detected signals</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="space-y-3">{Object.entries(result.languages).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([language, bytes]) => <div key={language}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium text-slate-700">{language}</span><span className="tnum text-slate-400">{languageTotal ? Math.round(bytes/languageTotal*100) : 0}%</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600" style={{ width: `${languageTotal ? Math.max(2, bytes/languageTotal*100) : 0}%` }} /></div></div>)}</div><div className="flex flex-wrap content-start gap-2">{result.technologies.map((technology) => <div key={technology.name} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"><span className="block text-[9px] font-semibold uppercase tracking-wider text-slate-400">{technology.category}</span><strong className="mt-1 block text-sm text-slate-800">{technology.name}</strong></div>)}</div></div></section>

        <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Architecture reading</p><h3 className="mt-2 text-xl font-semibold text-slate-900">{result.architecture.purpose}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{result.architecture.overview}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{result.architecture.majorModules.slice(0,8).map((module) => <div key={module} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-700">{module}</div>)}</div></div><div className="rounded-xl bg-[#eef1eb] p-5"><h4 className="text-sm font-semibold text-slate-900">Complexity indicators</h4><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Top-level areas</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.topLevelAreas}</dd></div><div><dt className="text-slate-400">Languages</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.languages}</dd></div><div><dt className="text-slate-400">Boundaries</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.architecturalBoundaries}</dd></div><div><dt className="text-slate-400">Test files</dt><dd className="mt-1 text-lg font-semibold text-slate-900">{result.complexity.testFiles}</dd></div></dl>{result.complexity.signals.length > 0 && <ul className="mt-4 space-y-2">{result.complexity.signals.map((signal) => <li key={signal} className="flex gap-2 text-xs text-slate-600"><span className="text-brand-700">✓</span>{signal}</li>)}</ul>}</div></section>

        {result.strengths.length > 0 && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Grounded strengths</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{result.strengths.map((strength) => <article key={strength.title} className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4"><h4 className="text-sm font-semibold text-emerald-950">{strength.title}</h4><p className="mt-2 text-xs leading-5 text-emerald-800">{strength.explanation}</p><code className="mt-3 block break-all text-[10px] text-emerald-700">{strength.files.join(" · ")}</code></article>)}</div></section>}

        <section><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Implementation evidence</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Patterns found in real source files</h3></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{result.patterns.map((pattern) => <article key={pattern.name} className="rounded-xl border border-slate-200 p-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-brand-700">{pattern.category}</span><h4 className="mt-3 text-sm font-semibold text-slate-900">{pattern.name}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{pattern.summary}</p><code className="mt-3 block break-all text-[10px] text-slate-400">{pattern.files.slice(0,3).join(" · ")}</code></article>)}</div></section>

        <section><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Skill evidence</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Implementation depth by skill</h3><p className="mt-2 text-xs text-slate-400">Strong=4, Good=3, Partial=2, Limited=1. Dependency-only signals cannot exceed Limited.</p></div><div className="mt-5 space-y-3">{result.skills.map((skill) => <details key={skill.skill} className="group rounded-xl border border-slate-200 bg-white open:border-brand-200"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><strong className="text-sm text-slate-900">{skill.skill}</strong><p className="mt-1 text-xs text-slate-500">{skill.explanation}</p></div><Badge tone={evidenceTone(skill.level)}>{skill.level}</Badge></summary><div className="grid gap-px border-t border-slate-100 bg-slate-100 md:grid-cols-2">{skill.evidence.map((evidence, index) => <div key={`${evidence.file}-${index}`} className="bg-white p-4"><code className="break-all text-[10px] font-semibold text-brand-700">{evidence.file}</code><strong className="mt-2 block text-xs text-slate-800">{evidence.summary}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{evidence.implementationExample}</p></div>)}</div></details>)}</div></section>

        {result.resumeVerification && <section><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">CV verification</p><h3 className="mt-2 text-xl font-semibold text-slate-900">Claims compared with this repository</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{result.resumeVerification.claims.map((claim) => <article key={`${claim.claim}-${claim.support}`} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><strong className="text-sm text-slate-900">{claim.claim}</strong><Badge tone={supportTone(claim.support)}>{claim.support}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">{claim.explanation}</p>{claim.files.length > 0 && <code className="mt-3 block break-all text-[10px] text-brand-700">{claim.files.join(" · ")}</code>}</article>)}</div></section>}

        <section className="grid gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-amber-700">Evidence gaps</p><div className="mt-4 space-y-2">{result.gaps.map((gap) => <div key={gap.area} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><strong className="text-sm text-amber-950">{gap.area}</strong><p className="mt-1 text-xs leading-5 text-amber-800">{gap.explanation}</p></div>)}</div></div><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-700">Interview prompts</p><ol className="mt-4 space-y-2">{result.interviewQuestions.map((question, index) => <li key={`${question.question}-${index}`} className="rounded-lg border border-slate-200 p-4"><div className="flex gap-2 text-[9px] font-semibold uppercase tracking-wider text-slate-400"><span>{question.difficulty}</span><span>·</span><span>{question.relatedSkill}</span></div><strong className="mt-2 block text-sm leading-6 text-slate-900">{question.question}</strong><code className="mt-2 block break-all text-[10px] text-brand-700">{question.files.join(" · ")}</code></li>)}</ol></div></section>
      </div>
    </article>
  );
}
